import * as z from 'zod';

export const PostcodeResponseSchema = z.object({
  postcode: z.string(),
  quality: z.number(),
  eastings: z.number(),
  northings: z.number(),
  country: z.string(),
  nhs_ha: z.string(),
  longitude: z.number().min(-180).max(180),
  latitude: z.number().min(-90).max(90),
  european_electoral_region: z.string(),
  primary_care_trust: z.string(),
  region: z.string(),
  lsoa: z.string(),
  msoa: z.string(),
  incode: z.string().min(3).max(4),
  outcode: z.string().min(3).max(4),
  parliamentary_constituency: z.string(),
  parliamentary_constituency_2024: z.string(),
  admin_district: z.string(),
  parish: z.string(),
  admin_county: z.string(),
  date_of_introduction: z.string(),
  admin_ward: z.string(),
  ced: z.string(),
  ccg: z.string(),
  nuts: z.string(),
  pfa: z.string(),
  codes: z.object({
    admin_district: z.string(),
    admin_county: z.string(),
    admin_ward: z.string(),
    parish: z.string(),
    parliamentary_constituency: z.string(),
    parliamentary_constituency_2024: z.string(),
    ccg: z.string(),
    ccg_id: z.string(),
    ced: z.string(),
    nuts: z.string(),
    lsoa: z.string(),
    msoa: z.string(),
    lau2: z.string(),
    pfa: z.string(),
  }),
});
